### ISSUE TITLE
Is `git checkout` still necessary?

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-booster-catalog-service#31]
The class `NativeGitBoosterCatalogPathProvider ` does a [`git checkout`](https://github.com/fabric8-launcher/launcher-booster-catalog-service/blob/master/src/main/java/io/fabric8/launcher/booster/catalog/spi/NativeGitBoosterCatalogPathProvider.java#L91) just after having done a [`git clone --branch`](https://github.com/fabric8-launcher/launcher-booster-catalog-service/blob/master/src/main/java/io/fabric8/launcher/booster/catalog/spi/NativeGitBoosterCatalogPathProvider.java#L82). That seems unnecessary.

**Comment by quintesse** [comment]
@gastaldi I don't see any reason to do this. Are you aware of any reason why this is/was necessary?

**Comment by gastaldi** [comment]
If remember correctly that was necessary because gitRef could be a tag/branch/commit hash.

**Comment by quintesse** [comment]
Aha, thanks! Let me check if that's correct and then I'll close this issue.

**Comment by quintesse** [comment]
Ok true, it doesn't support commit hashes (it does support tags). Closing.

**Comment by quintesse** [comment]
Hmmm wait, but the `git clone --branch` fails with an error if you pass it a commit hash, so this can't have worked. Are we using commit hashes for this somewhere @gastaldi ?

**Comment by gastaldi** [comment]
I don't think we are, I don't remember how I tested that exactly

**Comment by quintesse** [comment]
Ok, just tested it, commit hashes are not supported.

**Comment by matskiv** [comment]
@quintesse @gastaldi btw: catalog Readme still states that you support hashes: https://github.com/fabric8-launcher/launcher-booster-catalog#booster-descriptor
So based on your discussion here, it officially unsupported? If so, I can send a PR to update the Readme :)

**Comment by gastaldi** [comment]
@matskiv good catch, SHA1 is not supported. A PR would be lovely! Thank you!
